name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag http-build
      
    - name: Run the Docker image
      run: docker run --name myhttpd -p 80:80 -d http-build
      
    - name: Check container running
      run: docker ls
